# Generated by Django 3.2.5 on 2021-07-21 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('phone_number', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=300)),
                ('engine_size', models.DecimalField(decimal_places=4, max_digits=8)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_car_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('altitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='driver_car_app.truck')),
            ],
        ),
    ]
