# Generated by Django 3.2.5 on 2021-07-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_car_app', '0002_rename_phone_number_driver_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(choices=[('Volvo', 'Volvo'), ('Opel', 'Opel')], max_length=32)),
            ],
        ),
    ]
