# Generated by Django 3.2.5 on 2021-07-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_car_app', '0003_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='driver_car_app.brand'),
        ),
    ]
