# Generated by Django 3.2.5 on 2021-07-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_car_app', '0004_truck_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='model',
            new_name='truck_name',
        ),
    ]
